def makeConfigFile(dataset,  data, uidir, dir, sample):

    config='[CRAB]\n'
    config+='\n'
    config+='jobtype = cmssw\n'
    config+='scheduler = remoteGlidein\n'
    config+='#scheduler = glite\n'
    config+='### NOTE: just setting the name of the server (pi, lnl etc etc )\n'
    config+='###       crab will submit the jobs to the server...\n'
    config+='use_server = 0\n'
    config+='\n'
    config+='[CMSSW]\n'
    config+='\n'
    config+='###### Majorana signal samples ######\n'
    config+='datasetpath=' + dataset + '\n'
    config+='\n'
    config+='### The ParameterSet you want to use\n'
    config+='pset = rootTupleMaker_MC_2012_53X_cfg.py\n' 
    config+='\n'
    config+='### Splitting parameters\n'
    config+='total_number_of_events=-1\n'
    config+='events_per_job = 20000\n'
    config+='\n'
    config+='### The output files (comma separated list)\n'
    config+='output_file = file.root\n'
    config+='\n'
    config+='\n'
    config+='[USER]\n'
    config+='thresholdLevel          = 100\n'
    config+='use_central_bossDB      = 0\n'
    config+='use_boss_rt             = 0\n'
    config+='email =jalmond@cern.ch\n'
    config+='\n'
    config+='\n'
    config+='### OUTPUT files Management\n'
    config+='##  output back into UI\n'
    config+='ui_working_dir =  ' + dir + "/" + uidir +'\n'
    config+='return_data = 0\n'
    config+='\n'
    config+='\n'
    config+='## OUTPUT files INTO A SE\n'
    config+='copy_data = 1\n'
    config+='\n'
    config+='### if you want to copy data in a "official CMS site"\n'
    config+='### you have to specify the name as written in \n'
    config+='\n'
#    config+='storage_element = T3_KR_UOS\n'
    config+='storage_element = T3_KR_KISTI\n'
    config+='user_remote_dir = Summer12_tag18/LQ_2016_April_'+uidir+'\n'
    config+='\n'
    config+='### To publish produced output in a local istance of DBS set publish_data = 1\n'
    config+='publish_data = 1\n'
    config+='publish_data_name = LQNtupleSNU2016_MCApril\n' 
    config+='\n'
    config+='#### Specify the dataset name. The full path will be <primarydataset>/<publish_data_name>/USER\n'
    config+='\n'
    config+='eMail = jalmond@cern.ch\n'
    config+='[GRID]\n'
    config+='\n'
    config+='#se_black_list = T2_DE_DESY,T2_UK_London_Brunel\n'
    config+='#se_white_list = T2_PK_NCP\n'
    config+='\n'

    
    return config
